app:
  issuer-url: ${ISSUER_URL}

server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always